# Generated by Django 4.2.20 on 2025-07-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('email', models.CharField(default='example@email.com', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('hallno', models.CharField(max_length=3, null=True)),
                ('hallname', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=11, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('isLoggedIn', models.CharField(default='False', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_no', models.IntegerField(null=True)),
                ('hall_name', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelComplaints',
            fields=[
                ('complaint_id', models.CharField(default='00000000', max_length=50, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('complaint', models.CharField(max_length=2500, null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('room_no', models.IntegerField(null=True)),
                ('addressed', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessComplaints',
            fields=[
                ('complaint_id', models.CharField(default='00000000', max_length=50, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('complaint', models.CharField(max_length=2500, null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('addressed', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaymentDetails',
            fields=[
                ('payment_id', models.CharField(default='00000000', max_length=50, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('bank_account_no', models.CharField(max_length=50, null=True)),
                ('hostelpayment', models.IntegerField(null=True)),
                ('messpayment', models.IntegerField(null=True)),
                ('fine', models.IntegerField(null=True)),
                ('refund', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(default='00000000', max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('year', models.IntegerField(null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('hall_name', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=11, null=True)),
                ('phonenumber1', models.CharField(max_length=11, null=True)),
                ('phonenumber2', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('room_no', models.IntegerField(null=True)),
            ],
        ),
    ]
