# Generated by Django 4.2.20 on 2025-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallno', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
