# Generated by Django 4.2.20 on 2025-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='isLoggedIn',
            field=models.CharField(default='False', max_length=3, null=True),
        ),
    ]
