# Generated by Django 4.2.20 on 2025-04-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorities',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorities',
            name='hallname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorities',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorities',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='authorities',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authorities',
            name='hallno',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='authorities',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
