# Generated by Django 4.2.20 on 2025-04-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_authorities_email_authorities_hallname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True, unique=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('bank_account_no', models.CharField(max_length=50, null=True)),
                ('hostelpayment', models.IntegerField(null=True)),
                ('messpayment', models.IntegerField(null=True)),
                ('fine', models.IntegerField(null=True)),
                ('refund', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('student_id', models.CharField(max_length=50, null=True, unique=True)),
                ('year', models.IntegerField(null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('hall_name', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=11, null=True)),
                ('phonenumber1', models.CharField(max_length=11, null=True)),
                ('phonenumber2', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('room_no', models.IntegerField(null=True)),
                ('check_in', models.DateField(null=True)),
                ('check_out', models.DateField(null=True)),
            ],
        ),
    ]
