# Generated by Django 4.2.20 on 2025-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_students_isloggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorities',
            name='isLoggedIn',
            field=models.CharField(default='NO', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='isLoggedIn',
            field=models.CharField(default='NO', max_length=3, null=True),
        ),
    ]
