# Generated by Django 4.2.20 on 2025-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_studentpaymentdetails_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_no', models.IntegerField(null=True)),
                ('hall_name', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
