# Generated by Django 4.2.20 on 2025-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0004_halldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('complaint', models.CharField(max_length=2500, null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('room_no', models.IntegerField(null=True)),
                ('addressed', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('complaint', models.CharField(max_length=2500, null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('addressed', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
