# Generated by Django 4.2.20 on 2025-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_hostelcomplaints_messcomplaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='branch',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
