# Generated by Django 4.2.20 on 2025-04-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0006_rename_branch_students_degree_students_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='students',
            name='check_out',
        ),
    ]
