# Generated by Django 4.2.20 on 2025-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0007_remove_students_check_in_remove_students_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='halldetails',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
